version: '2'
services:
    web:
        build:
            context: .
            dockerfile: ./web.docker
        volumes:
            - ../:/var/www
        ports:
            - "8080:80"
        links:
            - app_sqeezin
        depends_on:
            - app_sqeezin
    app_sqeezin:
        build:
            context: .
            dockerfile: ./app.docker
        volumes:
            - ../:/var/www
        links:
            - database
        environment:
            - "DB_PORT=3306"
            - "DB_HOST=database"
    database:
        image: mysql:5.6
        environment:
            - "MYSQL_ROOT_PASSWORD=password"
        ports:
            - "33062:3306"
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        environment:
            - "PMA_HOST=database"
            - "PMA_USER=root"
            - "PMA_PASSWORD=password"
            - "MYSQL_ROOT_PASSWORD=password"
        ports:
            - "8088:80"
